version: 2

project_name: kubectl-analyze-images

before:
  hooks:
    - go mod tidy

builds:
  - id: kubectl-analyze-images
    main: ./cmd/kubectl-analyze-images
    binary: kubectl-analyze-images
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: ronaknnathani
    name: kubectl-analyze-images
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
